# Proxy / Edge
rtspAddress: :8554

# Não precisamos servir HLS/WebRTC aqui (fica no central).
hls: no
webrtc: no

# API para reload de config via cam-bus.
# Para proteger o endpoint, configure authInternalUsers (MediaMTX recente).
# Se habilitar auth, o cam-bus precisa enviar essas credenciais no reload.
api: yes
apiAddress: :9997

# authInternalUsers:
#   # Mantém publish/read/playback abertos (equivalente ao comportamento default).
#   - user: any
#     permissions:
#       - action: publish
#       - action: read
#       - action: playback
#   # Usuário dedicado ao acesso da API
#   - user: admin
#     pass: secret
#     permissions:
#       - action: api

# (Opcional) habilitar playback depois (pra exportar MP4 de um intervalo via /get).
# playback: yes
# playbackAddress: :9996

pathDefaults:
  # Para gravação constante:
  record: yes
  recordPath: /recordings/%path/%Y-%m-%d_%H-%M-%S-%f
  recordFormat: fmp4
  recordPartDuration: 1s
  recordSegmentDuration: 1m
  recordDeleteAfter: 0s   # 0s = não apaga automaticamente (ajuste depois)
  # Se quiser retenção: 24h, 7d etc.

paths: {}
